services:

  app:
    build: .
    environment:
      PORT: 3000
      DATABASE: mydatabase
      DATABASE_USER: ${POSTGRES_USER:-postgres}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DATABASE_HOST: postgres
    ports:
      - '3000:3000'
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: mydatabase
      PGDATA: /data/mydatabase
    volumes:
      - pgstore:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:6.5
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '5050:80'
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  pgstore:
  pgadmin:
